simulation:
  max_steps: 10_000
  max_time: 100000000
  max_cells: 5_000
  seed: 7

mutation_store:
  source: ":memory:"

mutation_generator:
  type: uniform

rate_function:
  type: weighted_sum
  baseline_birth_rate: 0.8
  baseline_death_rate: 0.1
  carrying_capacity: 500

plugins:
  erk_pathway:
    type: erk_pathway
    target: rate_function
    category: proliferative
    weight: 1.0
    alpha: 0.0

  melanocyte_ois:
    type: melanocyte_ois
    target: senescence
    weight: 1.0
    alpha: 0.0

  mutation_rate:
    type: constant_mutation_rate
    target: mutation_rate
    weight: 1.0
    alpha: 0.0
    params:
      mu: 1.0

recorder:
  output_dir: results/
  snapshot_interval: 5
  dump_final_state: true
