base_config: evoseer/config/erk_ois.yaml

n_samples: 10
n_sims: 100
epsilon: 0.1
distance: ks
base_seed: 42

target:
  data_dir: /home/ben/projects/EvoSeerEngine/ISIC_2024

priors:
  erk_pathway:
    weight: [uniform, 0.0, 3.0]
    alpha:  [uniform, -1.0, 1.0]
  base_death:
    weight: [uniform, 0.0, 3.0]
    alpha:  [uniform,  0.0, 2.0]
