base_config: evoseer/config/erk_ois.yaml

n_samples: 10
max_sims: 50
epsilon: 1
distance: MSE
base_seed: 42
smoothing_window : 10

stages: 
  - [0.1, 5]
  - [0.05, 2.5]
  - [0.01, 1.0]

target:
  data_dir: /home/ben/projects/EvoSeerEngine/ISIC_2024

priors:
  rate_function:
    carrying_capacity:   [uniform, 100, 500]
